geographies:
- REGION
- TAZ
seed_geography: TAZ
total_hh_control: num_hh_taz
input_table_list:
- tablename: households
  filename: seed_households.csv
  index_col: household_id
- tablename: persons
  filename: seed_persons.csv
  index_col: person_id
- tablename: geo_cross_walk
  filename: geo_cross_walk.csv
- tablename: TAZ_control_data
  filename: control_totals_taz.csv
- tablename: REGION_control_data
  filename: control_totals_region.csv
household_weight_col: sample_weight
household_id_col: household_id
output_tables:
  action: include
  tables:
  - summary
  - expanded_household_ids
output_synthetic_population:
  households:
    filename: synthetic_households.csv
    columns:
    - household_id
    - home_zone_id
    - hhsize
    - HHT
    - income
    - auto_ownership
    - num_workers
    - sample_weight
    - REGION
    - TAZ
  persons:
    filename: synthetic_persons.csv
    columns:
    - household_id
    - home_zone_id
    - age
    - PNUM
    - sex
    - pemploy
    - pstudent
    - ptype
    - has_license
    - workplace_zone_id
    - school_zone_id
models:
- input_pre_processor
- setup_data_structures
- initial_seed_balancing
- meta_control_factoring
- final_seed_balancing
- integerize_final_seed_weights
- expand_households
- write_tables
- write_synthetic_population
